import 'package:flutter/material.dart';

enum PigeonRarity {
  common('Commun', 'Common', Color(0xFF8A8A78)),
  rare('Rare', 'Rare', Color(0xFF4D8BB8)),
  epic('Épique', 'Epic', Color(0xFF9A68AD)),
  legendary('Légendaire', 'Legendary', Color(0xFFD49A35));

  const PigeonRarity(this.frenchLabel, this.englishLabel, this.color);
  final String frenchLabel;
  final String englishLabel;
  final Color color;
  String label(bool isFrench) => isFrench ? frenchLabel : englishLabel;
}

enum VisitPeriod { any, morning, night }

class Pigeon {
  const Pigeon({
    required this.id,
    required this.number,
    required this.name,
    required this.rarity,
    required this.hintFr,
    required this.hintEn,
    required this.descriptionFr,
    required this.descriptionEn,
    required this.color,
    this.foodIds = const [],
    this.decorationIds = const [],
    this.period = VisitPeriod.any,
    this.accessory,
  });

  final String id;
  final int number;
  final String name;
  final PigeonRarity rarity;
  final String hintFr;
  final String hintEn;
  final String descriptionFr;
  final String descriptionEn;
  final Color color;
  final List<String> foodIds;
  final List<String> decorationIds;
  final VisitPeriod period;
  final IconData? accessory;

  String hint(bool isFrench) => isFrench ? hintFr : hintEn;
  String description(bool isFrench) => isFrench ? descriptionFr : descriptionEn;
}

const pigeons = <Pigeon>[
  Pigeon(
    id: 'gilbert',
    number: 1,
    name: 'Gilbert',
    rarity: PigeonRarity.common,
    hintFr: 'Quelques graines suffisent.',
    hintEn: 'A few seeds will do.',
    descriptionFr: 'Il adore les graines et les commérages.',
    descriptionEn: 'He loves seeds and gossip.',
    color: Color(0xFF87939A),
    foodIds: ['seeds'],
  ),
  Pigeon(
    id: 'michel',
    number: 2,
    name: 'Michel',
    rarity: PigeonRarity.common,
    hintFr: 'Une tranche classique.',
    hintEn: 'A classic slice.',
    descriptionFr: 'Il ne rate jamais l’heure du goûter.',
    descriptionEn: 'He never misses snack time.',
    color: Color(0xFFA3AAA7),
    foodIds: ['bread'],
  ),
  Pigeon(
    id: 'chonky',
    number: 3,
    name: 'Chonky',
    rarity: PigeonRarity.common,
    hintFr: 'Plus il y en a, mieux c’est.',
    hintEn: 'The more, the better.',
    descriptionFr: 'Petit par la taille, immense par l’appétit.',
    descriptionEn: 'Small in size, enormous in appetite.',
    color: Color(0xFF6F7474),
    foodIds: ['fries', 'pizza'],
  ),
  Pigeon(
    id: 'kevin',
    number: 4,
    name: 'Kevin',
    rarity: PigeonRarity.rare,
    hintFr: 'Des témoins parlent de frites.',
    hintEn: 'Witnesses mentioned fries.',
    descriptionFr: 'On le reconnaît au bruit des frites qui disparaissent.',
    descriptionEn: 'Recognizable by the sound of disappearing fries.',
    color: Color(0xFF8A9AA0),
    foodIds: ['fries'],
    accessory: Icons.fastfood_outlined,
  ),
  Pigeon(
    id: 'brenda',
    number: 5,
    name: 'Brenda',
    rarity: PigeonRarity.rare,
    hintFr: 'Elle cherche un endroit où se poser.',
    hintEn: 'She needs somewhere to sit.',
    descriptionFr: 'Élégante et toujours parfaitement coiffée.',
    descriptionEn: 'Elegant and always perfectly groomed.',
    color: Color(0xFF547488),
    decorationIds: ['bench'],
  ),
  Pigeon(
    id: 'jean_pigeon',
    number: 6,
    name: 'Jean-Pigeon',
    rarity: PigeonRarity.rare,
    hintFr: 'Une odeur de boulangerie flotte dans l’air.',
    hintEn: 'The air smells like a bakery.',
    descriptionFr: 'Un grand voyageur amateur de baguettes.',
    descriptionEn: 'A great traveller fond of baguettes.',
    color: Color(0xFFF1EEE1),
    foodIds: ['bread'],
    decorationIds: ['baguette_stand'],
  ),
  Pigeon(
    id: 'croissigeon',
    number: 7,
    name: 'Croissigeon',
    rarity: PigeonRarity.epic,
    hintFr: 'Le petit-déjeuner se prend tôt.',
    hintEn: 'Breakfast comes early.',
    descriptionFr: 'Toujours feuilleté, jamais pressé.',
    descriptionEn: 'Always flaky, never hurried.',
    color: Color(0xFFD5A36C),
    foodIds: ['croissant'],
    period: VisitPeriod.morning,
  ),
  Pigeon(
    id: 'pigeoffrey',
    number: 8,
    name: 'Pigeoffrey',
    rarity: PigeonRarity.epic,
    hintFr: 'Il apprécie le bruit de l’eau.',
    hintEn: 'He enjoys the sound of water.',
    descriptionFr: 'Il médite longuement près des fontaines.',
    descriptionEn: 'He meditates beside fountains.',
    color: Color(0xFF7395A5),
    decorationIds: ['fountain'],
  ),
  Pigeon(
    id: 'gothigeon',
    number: 9,
    name: 'Gothigeon',
    rarity: PigeonRarity.epic,
    hintFr: 'Le soleil n’est pas son ami.',
    hintEn: 'Sunlight is not a friend.',
    descriptionFr: 'Son plumage est aussi sombre que ses poèmes.',
    descriptionEn: 'His feathers are as dark as his poems.',
    color: Color(0xFF44414A),
    period: VisitPeriod.night,
  ),
  Pigeon(
    id: 'disco_pigeon',
    number: 10,
    name: 'Disco Pigeon',
    rarity: PigeonRarity.epic,
    hintFr: 'La musique prend vie après minuit.',
    hintEn: 'Music comes alive after midnight.',
    descriptionFr: 'Le roi incontesté du dancefloor municipal.',
    descriptionEn: 'Undisputed king of the municipal dance floor.',
    color: Color(0xFFB06FA7),
    decorationIds: ['radio'],
    period: VisitPeriod.night,
    accessory: Icons.music_note,
  ),
  Pigeon(
    id: 'pigeasso',
    number: 11,
    name: 'Pigeasso',
    rarity: PigeonRarity.epic,
    hintFr: 'Une toile blanche attend son génie.',
    hintEn: 'A blank canvas awaits genius.',
    descriptionFr: 'Il peint exclusivement avec ses pattes.',
    descriptionEn: 'He paints exclusively with his feet.',
    color: Color(0xFF6D91A7),
    decorationIds: ['easel'],
    accessory: Icons.palette_outlined,
  ),
  Pigeon(
    id: 'sherlock',
    number: 12,
    name: 'Sherlock',
    rarity: PigeonRarity.epic,
    hintFr: 'Toute enquête commence sous une bonne lumière.',
    hintEn: 'Every case begins under a good light.',
    descriptionFr: 'Aucun mystère de miette ne lui résiste.',
    descriptionEn: 'No crumb mystery can resist him.',
    color: Color(0xFF806B58),
    decorationIds: ['lamp'],
    accessory: Icons.search,
  ),
  Pigeon(
    id: 'pigeonzilla',
    number: 13,
    name: 'Pigeonzilla',
    rarity: PigeonRarity.epic,
    hintFr: 'Il faut beaucoup de nourriture pour une grande ombre.',
    hintEn: 'A large shadow needs lots of food.',
    descriptionFr: 'Plus impressionnant de loin que de près.',
    descriptionEn: 'More impressive from afar than up close.',
    color: Color(0xFF708769),
    foodIds: ['premium_seeds'],
  ),
  Pigeon(
    id: 'pigeon_potter',
    number: 14,
    name: 'Pigeon Potter',
    rarity: PigeonRarity.legendary,
    hintFr: 'Un livre ouvert à la nuit tombée.',
    hintEn: 'An open book after nightfall.',
    descriptionFr: 'Il attend toujours sa lettre.',
    descriptionEn: 'He is still waiting for his letter.',
    color: Color(0xFF6A647A),
    decorationIds: ['books'],
    period: VisitPeriod.night,
    accessory: Icons.auto_fix_high,
  ),
  Pigeon(
    id: 'sir_pigeonton',
    number: 15,
    name: 'Sir Pigeonton',
    rarity: PigeonRarity.legendary,
    hintFr: 'Des goûts coûteux et un banc distingué.',
    hintEn: 'Expensive tastes and a distinguished bench.',
    descriptionFr: 'Il possède probablement davantage d’immobilier que toi.',
    descriptionEn: 'He probably owns more real estate than you.',
    color: Color(0xFF555A5B),
    foodIds: ['premium_seeds'],
    decorationIds: ['bench'],
    accessory: Icons.workspace_premium,
  ),
  Pigeon(
    id: 'don_pigeone',
    number: 16,
    name: 'Don Pigeone',
    rarity: PigeonRarity.legendary,
    hintFr: 'Une offre qu’il ne peut pas refuser… 🍕',
    hintEn: 'An offer he cannot refuse… 🍕',
    descriptionFr: 'Il règle toujours ses affaires après la tombée de la nuit.',
    descriptionEn: 'He handles business after dark.',
    color: Color(0xFF4D4B49),
    foodIds: ['pizza'],
    decorationIds: ['trash'],
    period: VisitPeriod.night,
    accessory: Icons.business_center,
  ),
  Pigeon(
    id: 'pigeoin',
    number: 17,
    name: 'Pigeoin',
    rarity: PigeonRarity.legendary,
    hintFr: 'Les pièces brillantes attirent son regard.',
    hintEn: 'Shiny coins catch his eye.',
    descriptionFr: 'Il connaît le cours de la miette en temps réel.',
    descriptionEn: 'He tracks crumb prices in real time.',
    color: Color(0xFFB89B52),
    accessory: Icons.monetization_on,
  ),
  Pigeon(
    id: 'napoleon',
    number: 18,
    name: 'Napoléon',
    rarity: PigeonRarity.legendary,
    hintFr: 'Une baguette face à une grande statue.',
    hintEn: 'A baguette before a grand statue.',
    descriptionFr: 'Petit pigeon, ambitions impériales.',
    descriptionEn: 'Small pigeon, imperial ambitions.',
    color: Color(0xFF687D91),
    foodIds: ['bread'],
    decorationIds: ['statue', 'baguette_stand'],
    accessory: Icons.flag,
  ),
  Pigeon(
    id: 'pigeon_exe',
    number: 19,
    name: 'Pigeon.exe',
    rarity: PigeonRarity.legendary,
    hintFr: 'Erreur 404 : condition introuvable.',
    hintEn: 'Error 404: condition not found.',
    descriptionFr: 'Il semble parfois traverser les bancs.',
    descriptionEn: 'He occasionally clips through benches.',
    color: Color(0xFF62A29B),
    accessory: Icons.memory,
  ),
  Pigeon(
    id: 'king_pigeon',
    number: 20,
    name: 'King Pigeon',
    rarity: PigeonRarity.legendary,
    hintFr: 'Le parc doit être digne d’une couronne.',
    hintEn: 'The park must be worthy of a crown.',
    descriptionFr: 'Tous les pigeons prétendent être ses cousins.',
    descriptionEn: 'Every pigeon claims to be his cousin.',
    color: Color(0xFFD0AD4F),
    accessory: Icons.workspace_premium,
  ),
  Pigeon(
    id: 'miette',
    number: 21,
    name: 'Miette',
    rarity: PigeonRarity.common,
    hintFr: 'Elle aime les fleurs simples.',
    hintEn: 'She likes simple flowers.',
    descriptionFr: 'Elle collectionne les pétales minuscules.',
    descriptionEn: 'She collects tiny petals.',
    color: Color(0xFFB9A2A7),
    decorationIds: ['flowers'],
  ),
  Pigeon(
    id: 'roger',
    number: 22,
    name: 'Roger',
    rarity: PigeonRarity.common,
    hintFr: 'Un banc et du calme.',
    hintEn: 'A bench and some peace.',
    descriptionFr: 'Il vient lire le journal sans journal.',
    descriptionEn: 'He comes to read a newspaper without one.',
    color: Color(0xFF8C887E),
    decorationIds: ['bench'],
  ),
  Pigeon(
    id: 'baguettine',
    number: 23,
    name: 'Baguettine',
    rarity: PigeonRarity.rare,
    hintFr: 'Le pain frais lui rappelle Paris.',
    hintEn: 'Fresh bread reminds her of Paris.',
    descriptionFr: 'Elle laisse toujours une miette en pourboire.',
    descriptionEn: 'She always leaves a crumb as a tip.',
    color: Color(0xFFD8C19B),
    foodIds: ['bread'],
  ),
  Pigeon(
    id: 'professeur_plume',
    number: 24,
    name: 'Professeur Plume',
    rarity: PigeonRarity.rare,
    hintFr: 'Il cherche une pile de livres.',
    hintEn: 'He seeks a stack of books.',
    descriptionFr: 'Ses conférences durent plusieurs roucoulements.',
    descriptionEn: 'His lectures last several coos.',
    color: Color(0xFF758596),
    decorationIds: ['books'],
    accessory: Icons.school_outlined,
  ),
  Pigeon(
    id: 'fleur',
    number: 25,
    name: 'Fleur',
    rarity: PigeonRarity.rare,
    hintFr: 'Un jardin parfumé suffit.',
    hintEn: 'A fragrant garden will do.',
    descriptionFr: 'Elle refuse catégoriquement de marcher dans la boue.',
    descriptionEn: 'She categorically refuses to walk in mud.',
    color: Color(0xFFC89AAB),
    decorationIds: ['flowers'],
    accessory: Icons.local_florist,
  ),
  Pigeon(
    id: 'radio_piaf',
    number: 26,
    name: 'Radio Piaf',
    rarity: PigeonRarity.epic,
    hintFr: 'Une radio pendant la journée.',
    hintEn: 'A radio during the day.',
    descriptionFr: 'Il connaît tous les refrains, rarement les paroles.',
    descriptionEn: 'He knows every tune, rarely the lyrics.',
    color: Color(0xFF7C6D91),
    decorationIds: ['radio'],
  ),
  Pigeon(
    id: 'monsieur_propre',
    number: 27,
    name: 'Monsieur Propre',
    rarity: PigeonRarity.epic,
    hintFr: 'Même une poubelle peut être élégante.',
    hintEn: 'Even a bin can be elegant.',
    descriptionFr: 'Il inspecte chaque miette avant de partir.',
    descriptionEn: 'He inspects every crumb before leaving.',
    color: Color(0xFFE2DDD2),
    decorationIds: ['trash'],
  ),
  Pigeon(
    id: 'minuit',
    number: 28,
    name: 'Minuit',
    rarity: PigeonRarity.epic,
    hintFr: 'Des fleurs visibles au clair de lune.',
    hintEn: 'Flowers beneath the moonlight.',
    descriptionFr: 'Elle disparaît toujours avant l’aube.',
    descriptionEn: 'She always vanishes before dawn.',
    color: Color(0xFF55566B),
    decorationIds: ['flowers'],
    period: VisitPeriod.night,
  ),
  Pigeon(
    id: 'capitaine_plume',
    number: 29,
    name: 'Capitaine Plume',
    rarity: PigeonRarity.legendary,
    hintFr: 'Un festin premium pour un grand voyage.',
    hintEn: 'A premium feast for a great voyage.',
    descriptionFr: 'Il connaît une île entièrement faite de miettes.',
    descriptionEn: 'He knows an island made entirely of crumbs.',
    color: Color(0xFF765747),
    foodIds: ['premium_seeds'],
    accessory: Icons.sailing,
  ),
  Pigeon(
    id: 'celeste',
    number: 30,
    name: 'Céleste',
    rarity: PigeonRarity.legendary,
    hintFr: 'La radio murmure parfois son nom près d’un festin rare.',
    hintEn: 'The radio sometimes whispers her name near a rare feast.',
    descriptionFr: 'Elle apparaît lorsque le parc devient parfaitement calme.',
    descriptionEn: 'She appears when the park becomes perfectly still.',
    color: Color(0xFF9E92B8),
    foodIds: ['premium_seeds'],
    decorationIds: ['radio'],
    period: VisitPeriod.night,
    accessory: Icons.auto_awesome,
  ),
];
