import 'package:flutter/material.dart';

enum PigeonRarity {
  common('Commun', 'Common', Color(0xFF8A8A78)),
  rare('Rare', 'Rare', Color(0xFF4D8BB8)),
  epic('Épique', 'Epic', Color(0xFF9A68AD)),
  legendary('Légendaire', 'Legendary', Color(0xFFD49A35));

  const PigeonRarity(this.frenchLabel, this.englishLabel, this.color);
  final String frenchLabel;
  final String englishLabel;
  final Color color;
  String label(bool isFrench) => isFrench ? frenchLabel : englishLabel;
}

enum VisitPeriod { any, morning, night }

enum PigeonWeather { any, sunny, cloudy, rainy }

class Pigeon {
  const Pigeon({
    required this.id,
    required this.number,
    required this.name,
    required this.rarity,
    required this.hintFr,
    required this.hintEn,
    required this.descriptionFr,
    required this.descriptionEn,
    required this.color,
    this.foodIds = const [],
    this.decorationIds = const [],
    this.period = VisitPeriod.any,
    this.weather = PigeonWeather.any,
    this.accessory,
  });

  final String id;
  final int number;
  final String name;
  final PigeonRarity rarity;
  final String hintFr;
  final String hintEn;
  final String descriptionFr;
  final String descriptionEn;
  final Color color;
  final List<String> foodIds;
  final List<String> decorationIds;
  final VisitPeriod period;
  final PigeonWeather weather;
  final IconData? accessory;

  String hint(bool isFrench) => isFrench ? hintFr : hintEn;
  String description(bool isFrench) => isFrench ? descriptionFr : descriptionEn;

  PigeonPersonality get personality => pigeonPersonalities[id]!;
}

class PigeonPersonality {
  const PigeonPersonality({
    required this.temperamentFr,
    required this.temperamentEn,
    required this.catchphraseFr,
    required this.catchphraseEn,
    required this.favoriteActivity,
  });

  final String temperamentFr;
  final String temperamentEn;
  final String catchphraseFr;
  final String catchphraseEn;
  final String favoriteActivity;

  String temperament(bool isFrench) => isFrench ? temperamentFr : temperamentEn;
  String catchphrase(bool isFrench) => isFrench ? catchphraseFr : catchphraseEn;
}

const pigeonPersonalities = <String, PigeonPersonality>{
  'gilbert': PigeonPersonality(
    temperamentFr: 'Sociable, curieux et incorrigiblement bavard.',
    temperamentEn: 'Sociable, curious, and hopelessly chatty.',
    catchphraseFr: 'Je ne colporte rien, je tiens le parc informé.',
    catchphraseEn: 'I do not gossip; I keep the park informed.',
    favoriteActivity: 'pet',
  ),
  'michel': PigeonPersonality(
    temperamentFr: 'Ponctuel, tranquille et très attaché à ses habitudes.',
    temperamentEn: 'Punctual, peaceful, and devoted to his routines.',
    catchphraseFr: 'Chaque miette en son temps.',
    catchphraseEn: 'Every crumb in its own time.',
    favoriteActivity: 'pet',
  ),
  'chonky': PigeonPersonality(
    temperamentFr: 'Jovial, gourmand et toujours prêt à jouer.',
    temperamentEn: 'Cheerful, greedy, and always ready to play.',
    catchphraseFr: 'Je gardais cette place pour le dessert.',
    catchphraseEn: 'I was saving that spot for dessert.',
    favoriteActivity: 'play',
  ),
  'kevin': PigeonPersonality(
    temperamentFr: 'Impulsif, enthousiaste et fier de ses mauvaises idées.',
    temperamentEn: 'Impulsive, enthusiastic, and proud of his bad ideas.',
    catchphraseFr: 'J’ai un plan. Il nous faut des frites.',
    catchphraseEn: 'I have a plan. We need fries.',
    favoriteActivity: 'play',
  ),
  'brenda': PigeonPersonality(
    temperamentFr: 'Assurée, élégante et secrètement très attentionnée.',
    temperamentEn: 'Confident, elegant, and secretly very caring.',
    catchphraseFr: 'Ce n’est pas poser, c’est avoir de la présence.',
    catchphraseEn: 'It is not posing; it is having presence.',
    favoriteActivity: 'photo',
  ),
  'jean_pigeon': PigeonPersonality(
    temperamentFr: 'Romantique, voyageur et nostalgique des terrasses.',
    temperamentEn: 'Romantic, well-travelled, and nostalgic for cafés.',
    catchphraseFr: 'Paris est toujours à une baguette d’ici.',
    catchphraseEn: 'Paris is always one baguette away.',
    favoriteActivity: 'photo',
  ),
  'croissigeon': PigeonPersonality(
    temperamentFr: 'Matinal, délicat et optimiste avant neuf heures.',
    temperamentEn: 'An early bird, delicate, and optimistic before nine.',
    catchphraseFr: 'Une belle journée commence en feuilleté.',
    catchphraseEn: 'A lovely day begins with flaky pastry.',
    favoriteActivity: 'pet',
  ),
  'pigeoffrey': PigeonPersonality(
    temperamentFr: 'Calme, contemplatif et difficile à déconcentrer.',
    temperamentEn: 'Calm, contemplative, and very hard to distract.',
    catchphraseFr: 'Écoute l’eau. Elle connaît le chemin.',
    catchphraseEn: 'Listen to the water. It knows the way.',
    favoriteActivity: 'music',
  ),
  'gothigeon': PigeonPersonality(
    temperamentFr: 'Mélancolique, sensible et plus tendre qu’il ne l’admet.',
    temperamentEn: 'Melancholy, sensitive, and softer than he admits.',
    catchphraseFr: 'Le ciel me comprend quand il fait gris.',
    catchphraseEn: 'The sky understands me when it is grey.',
    favoriteActivity: 'music',
  ),
  'disco_pigeon': PigeonPersonality(
    temperamentFr: 'Exubérant, généreux et incapable de rester immobile.',
    temperamentEn: 'Exuberant, generous, and incapable of standing still.',
    catchphraseFr: 'Même les miettes ont le rythme.',
    catchphraseEn: 'Even crumbs have rhythm.',
    favoriteActivity: 'music',
  ),
  'pigeasso': PigeonPersonality(
    temperamentFr: 'Créatif, imprévisible et dramatiquement inspiré.',
    temperamentEn: 'Creative, unpredictable, and dramatically inspired.',
    catchphraseFr: 'Ne bouge plus, tu gâches ma composition.',
    catchphraseEn: 'Do not move; you are ruining my composition.',
    favoriteActivity: 'photo',
  ),
  'sherlock': PigeonPersonality(
    temperamentFr: 'Méthodique, observateur et légèrement prétentieux.',
    temperamentEn: 'Methodical, observant, and slightly pretentious.',
    catchphraseFr: 'La miette manquante était un indice.',
    catchphraseEn: 'The missing crumb was a clue.',
    favoriteActivity: 'play',
  ),
  'pigeonzilla': PigeonPersonality(
    temperamentFr: 'Impressionnant, maladroit et étonnamment timide.',
    temperamentEn: 'Imposing, clumsy, and surprisingly shy.',
    catchphraseFr: 'Je faisais attention… vraiment.',
    catchphraseEn: 'I was being careful… honestly.',
    favoriteActivity: 'pet',
  ),
  'pigeon_potter': PigeonPersonality(
    temperamentFr: 'Rêveur, loyal et persuadé que la magie existe.',
    temperamentEn: 'Dreamy, loyal, and convinced that magic exists.',
    catchphraseFr: 'Ce n’était pas le vent. C’était magique.',
    catchphraseEn: 'That was not the wind. It was magic.',
    favoriteActivity: 'play',
  ),
  'sir_pigeonton': PigeonPersonality(
    temperamentFr: 'Distingué, exigeant et généreux avec panache.',
    temperamentEn: 'Distinguished, demanding, and flamboyantly generous.',
    catchphraseFr: 'La noblesse oblige. Les graines premium aussi.',
    catchphraseEn: 'Noblesse oblige. So do premium seeds.',
    favoriteActivity: 'photo',
  ),
  'don_pigeone': PigeonPersonality(
    temperamentFr: 'Taciturne, protecteur et très attaché à la famille.',
    temperamentEn: 'Taciturn, protective, and devoted to the family.',
    catchphraseFr: 'Ce parc prend soin des siens.',
    catchphraseEn: 'This park looks after its own.',
    favoriteActivity: 'pet',
  ),
  'pigeoin': PigeonPersonality(
    temperamentFr: 'Calculateur, vif et fasciné par tout ce qui brille.',
    temperamentEn: 'Calculating, sharp, and fascinated by shiny things.',
    catchphraseFr: 'La plume monte. Achète des miettes.',
    catchphraseEn: 'Feathers are up. Buy crumbs.',
    favoriteActivity: 'play',
  ),
  'napoleon': PigeonPersonality(
    temperamentFr: 'Ambitieux, autoritaire et beaucoup trop sûr de lui.',
    temperamentEn: 'Ambitious, bossy, and far too sure of himself.',
    catchphraseFr: 'Depuis ce banc, je vois déjà mon empire.',
    catchphraseEn: 'From this bench, I can already see my empire.',
    favoriteActivity: 'photo',
  ),
  'pigeon_exe': PigeonPersonality(
    temperamentFr: 'Logique, étrange et sujet à des élans de spontanéité.',
    temperamentEn: 'Logical, strange, and prone to bursts of spontaneity.',
    catchphraseFr: 'Roucoulement.exe a cessé de fonctionner.',
    catchphraseEn: 'Cooing.exe has stopped working.',
    favoriteActivity: 'music',
  ),
  'king_pigeon': PigeonPersonality(
    temperamentFr: 'Majestueux, théâtral et sincèrement responsable.',
    temperamentEn: 'Majestic, theatrical, and genuinely responsible.',
    catchphraseFr: 'Que chaque pigeon reçoive sa juste miette.',
    catchphraseEn: 'Let every pigeon receive its rightful crumb.',
    favoriteActivity: 'photo',
  ),
  'miette': PigeonPersonality(
    temperamentFr: 'Douce, minutieuse et émerveillée par les petites choses.',
    temperamentEn: 'Gentle, meticulous, and delighted by little things.',
    catchphraseFr: 'Regarde, ce pétale est presque parfait.',
    catchphraseEn: 'Look, this petal is nearly perfect.',
    favoriteActivity: 'pet',
  ),
  'roger': PigeonPersonality(
    temperamentFr:
        'Grognon, casanier et fidèle à ceux qui respectent son calme.',
    temperamentEn:
        'Grumpy, home-loving, and loyal to those who respect his peace.',
    catchphraseFr: 'De mon temps, les bancs étaient plus silencieux.',
    catchphraseEn: 'In my day, benches were quieter.',
    favoriteActivity: 'pet',
  ),
  'baguettine': PigeonPersonality(
    temperamentFr: 'Chaleureuse, spontanée et toujours prête à partager.',
    temperamentEn: 'Warm, spontaneous, and always ready to share.',
    catchphraseFr: 'Prends la dernière miette, j’insiste.',
    catchphraseEn: 'Take the last crumb, I insist.',
    favoriteActivity: 'play',
  ),
  'professeur_plume': PigeonPersonality(
    temperamentFr: 'Savant, patient et incapable de faire une réponse courte.',
    temperamentEn: 'Learned, patient, and incapable of giving a short answer.',
    catchphraseFr: 'Pour répondre, commençons par le commencement.',
    catchphraseEn: 'To answer that, let us begin at the beginning.',
    favoriteActivity: 'music',
  ),
  'fleur': PigeonPersonality(
    temperamentFr:
        'Raffinée, solaire et particulièrement exigeante sur la propreté.',
    temperamentEn:
        'Refined, sunny, and especially demanding about cleanliness.',
    catchphraseFr: 'Une fleur mérite mieux que des pattes boueuses.',
    catchphraseEn: 'A flower deserves better than muddy feet.',
    favoriteActivity: 'photo',
  ),
  'radio_piaf': PigeonPersonality(
    temperamentFr: 'Nostalgique, expressif et toujours en train de fredonner.',
    temperamentEn: 'Nostalgic, expressive, and always humming.',
    catchphraseFr: 'Je connais l’air. Pour les paroles, improvise.',
    catchphraseEn: 'I know the tune. Improvise the words.',
    favoriteActivity: 'music',
  ),
  'monsieur_propre': PigeonPersonality(
    temperamentFr: 'Maniaque, serviable et fier du travail bien fait.',
    temperamentEn: 'Fastidious, helpful, and proud of a job well done.',
    catchphraseFr: 'Une miette propre est une bonne miette.',
    catchphraseEn: 'A clean crumb is a good crumb.',
    favoriteActivity: 'play',
  ),
  'minuit': PigeonPersonality(
    temperamentFr: 'Discrète, mystérieuse et attentive aux confidences.',
    temperamentEn: 'Quiet, mysterious, and attentive to secrets.',
    catchphraseFr: 'La nuit garde mieux les secrets que moi.',
    catchphraseEn: 'The night keeps secrets better than I do.',
    favoriteActivity: 'music',
  ),
  'capitaine_plume': PigeonPersonality(
    temperamentFr: 'Aventureux, courageux et conteur notoirement peu fiable.',
    temperamentEn:
        'Adventurous, brave, and a notoriously unreliable storyteller.',
    catchphraseFr: 'La vague faisait au moins trois bancs de haut !',
    catchphraseEn: 'The wave was at least three benches high!',
    favoriteActivity: 'play',
  ),
  'celeste': PigeonPersonality(
    temperamentFr: 'Sereine, énigmatique et étrangement réconfortante.',
    temperamentEn: 'Serene, enigmatic, and strangely comforting.',
    catchphraseFr: 'Le parc parle doucement quand tout le monde écoute.',
    catchphraseEn: 'The park speaks softly when everyone listens.',
    favoriteActivity: 'music',
  ),
};

const pigeons = <Pigeon>[
  Pigeon(
    id: 'gilbert',
    number: 1,
    name: 'Gilbert',
    rarity: PigeonRarity.common,
    hintFr: 'Quelques graines suffisent.',
    hintEn: 'A few seeds will do.',
    descriptionFr: 'Il adore les graines et les commérages.',
    descriptionEn: 'He loves seeds and gossip.',
    color: Color(0xFF87939A),
    foodIds: ['seeds'],
  ),
  Pigeon(
    id: 'michel',
    number: 2,
    name: 'Michel',
    rarity: PigeonRarity.common,
    hintFr: 'Une tranche classique.',
    hintEn: 'A classic slice.',
    descriptionFr: 'Il ne rate jamais l’heure du goûter.',
    descriptionEn: 'He never misses snack time.',
    color: Color(0xFFA3AAA7),
    foodIds: ['bread'],
  ),
  Pigeon(
    id: 'chonky',
    number: 3,
    name: 'Chonky',
    rarity: PigeonRarity.common,
    hintFr: 'Plus il y en a, mieux c’est.',
    hintEn: 'The more, the better.',
    descriptionFr: 'Petit par la taille, immense par l’appétit.',
    descriptionEn: 'Small in size, enormous in appetite.',
    color: Color(0xFF6F7474),
    foodIds: ['fries', 'pizza'],
  ),
  Pigeon(
    id: 'kevin',
    number: 4,
    name: 'Kevin',
    rarity: PigeonRarity.rare,
    hintFr: 'Des témoins parlent de frites.',
    hintEn: 'Witnesses mentioned fries.',
    descriptionFr: 'On le reconnaît au bruit des frites qui disparaissent.',
    descriptionEn: 'Recognizable by the sound of disappearing fries.',
    color: Color(0xFF8A9AA0),
    foodIds: ['fries'],
    accessory: Icons.fastfood_outlined,
  ),
  Pigeon(
    id: 'brenda',
    number: 5,
    name: 'Brenda',
    rarity: PigeonRarity.rare,
    hintFr: 'Elle cherche un endroit où se poser.',
    hintEn: 'She needs somewhere to sit.',
    descriptionFr: 'Élégante et toujours parfaitement coiffée.',
    descriptionEn: 'Elegant and always perfectly groomed.',
    color: Color(0xFF547488),
    decorationIds: ['bench'],
  ),
  Pigeon(
    id: 'jean_pigeon',
    number: 6,
    name: 'Jean-Pigeon',
    rarity: PigeonRarity.rare,
    hintFr: 'Une odeur de boulangerie flotte dans l’air.',
    hintEn: 'The air smells like a bakery.',
    descriptionFr: 'Un grand voyageur amateur de baguettes.',
    descriptionEn: 'A great traveller fond of baguettes.',
    color: Color(0xFFF1EEE1),
    foodIds: ['bread'],
    decorationIds: ['baguette_stand'],
  ),
  Pigeon(
    id: 'croissigeon',
    number: 7,
    name: 'Croissigeon',
    rarity: PigeonRarity.epic,
    hintFr: 'Le petit-déjeuner se prend tôt.',
    hintEn: 'Breakfast comes early.',
    descriptionFr: 'Toujours feuilleté, jamais pressé.',
    descriptionEn: 'Always flaky, never hurried.',
    color: Color(0xFFD5A36C),
    foodIds: ['croissant'],
    period: VisitPeriod.morning,
  ),
  Pigeon(
    id: 'pigeoffrey',
    number: 8,
    name: 'Pigeoffrey',
    rarity: PigeonRarity.epic,
    hintFr: 'Il apprécie le bruit de l’eau.',
    hintEn: 'He enjoys the sound of water.',
    descriptionFr: 'Il médite longuement près des fontaines.',
    descriptionEn: 'He meditates beside fountains.',
    color: Color(0xFF7395A5),
    decorationIds: ['fountain'],
  ),
  Pigeon(
    id: 'gothigeon',
    number: 9,
    name: 'Gothigeon',
    rarity: PigeonRarity.epic,
    hintFr: 'Le soleil n’est pas son ami.',
    hintEn: 'Sunlight is not a friend.',
    descriptionFr: 'Son plumage est aussi sombre que ses poèmes.',
    descriptionEn: 'His feathers are as dark as his poems.',
    color: Color(0xFF44414A),
    period: VisitPeriod.night,
    weather: PigeonWeather.cloudy,
  ),
  Pigeon(
    id: 'disco_pigeon',
    number: 10,
    name: 'Disco Pigeon',
    rarity: PigeonRarity.epic,
    hintFr: 'La musique prend vie après minuit.',
    hintEn: 'Music comes alive after midnight.',
    descriptionFr: 'Le roi incontesté du dancefloor municipal.',
    descriptionEn: 'Undisputed king of the municipal dance floor.',
    color: Color(0xFFB06FA7),
    decorationIds: ['radio'],
    period: VisitPeriod.night,
    accessory: Icons.music_note,
  ),
  Pigeon(
    id: 'pigeasso',
    number: 11,
    name: 'Pigeasso',
    rarity: PigeonRarity.epic,
    hintFr: 'Une toile blanche attend son génie.',
    hintEn: 'A blank canvas awaits genius.',
    descriptionFr: 'Il peint exclusivement avec ses pattes.',
    descriptionEn: 'He paints exclusively with his feet.',
    color: Color(0xFF6D91A7),
    decorationIds: ['easel'],
    accessory: Icons.palette_outlined,
  ),
  Pigeon(
    id: 'sherlock',
    number: 12,
    name: 'Sherlock',
    rarity: PigeonRarity.epic,
    hintFr: 'Toute enquête commence sous une bonne lumière.',
    hintEn: 'Every case begins under a good light.',
    descriptionFr: 'Aucun mystère de miette ne lui résiste.',
    descriptionEn: 'No crumb mystery can resist him.',
    color: Color(0xFF806B58),
    decorationIds: ['lamp'],
    accessory: Icons.search,
  ),
  Pigeon(
    id: 'pigeonzilla',
    number: 13,
    name: 'Pigeonzilla',
    rarity: PigeonRarity.epic,
    hintFr: 'Il faut beaucoup de nourriture pour une grande ombre.',
    hintEn: 'A large shadow needs lots of food.',
    descriptionFr: 'Plus impressionnant de loin que de près.',
    descriptionEn: 'More impressive from afar than up close.',
    color: Color(0xFF708769),
    foodIds: ['premium_seeds'],
  ),
  Pigeon(
    id: 'pigeon_potter',
    number: 14,
    name: 'Pigeon Potter',
    rarity: PigeonRarity.legendary,
    hintFr: 'Un livre ouvert à la nuit tombée.',
    hintEn: 'An open book after nightfall.',
    descriptionFr: 'Il attend toujours sa lettre.',
    descriptionEn: 'He is still waiting for his letter.',
    color: Color(0xFF6A647A),
    decorationIds: ['books'],
    period: VisitPeriod.night,
    accessory: Icons.auto_fix_high,
  ),
  Pigeon(
    id: 'sir_pigeonton',
    number: 15,
    name: 'Sir Pigeonton',
    rarity: PigeonRarity.legendary,
    hintFr: 'Des goûts coûteux et un banc distingué.',
    hintEn: 'Expensive tastes and a distinguished bench.',
    descriptionFr: 'Il possède probablement davantage d’immobilier que toi.',
    descriptionEn: 'He probably owns more real estate than you.',
    color: Color(0xFF555A5B),
    foodIds: ['premium_seeds'],
    decorationIds: ['bench'],
    accessory: Icons.workspace_premium,
  ),
  Pigeon(
    id: 'don_pigeone',
    number: 16,
    name: 'Don Pigeone',
    rarity: PigeonRarity.legendary,
    hintFr: 'Une offre qu’il ne peut pas refuser… 🍕',
    hintEn: 'An offer he cannot refuse… 🍕',
    descriptionFr: 'Il règle toujours ses affaires après la tombée de la nuit.',
    descriptionEn: 'He handles business after dark.',
    color: Color(0xFF4D4B49),
    foodIds: ['pizza'],
    decorationIds: ['trash'],
    period: VisitPeriod.night,
    accessory: Icons.business_center,
  ),
  Pigeon(
    id: 'pigeoin',
    number: 17,
    name: 'Pigeoin',
    rarity: PigeonRarity.legendary,
    hintFr: 'Les pièces brillantes attirent son regard.',
    hintEn: 'Shiny coins catch his eye.',
    descriptionFr: 'Il connaît le cours de la miette en temps réel.',
    descriptionEn: 'He tracks crumb prices in real time.',
    color: Color(0xFFB89B52),
    accessory: Icons.monetization_on,
  ),
  Pigeon(
    id: 'napoleon',
    number: 18,
    name: 'Napoléon',
    rarity: PigeonRarity.legendary,
    hintFr: 'Une baguette face à une grande statue.',
    hintEn: 'A baguette before a grand statue.',
    descriptionFr: 'Petit pigeon, ambitions impériales.',
    descriptionEn: 'Small pigeon, imperial ambitions.',
    color: Color(0xFF687D91),
    foodIds: ['bread'],
    decorationIds: ['statue', 'baguette_stand'],
    accessory: Icons.flag,
  ),
  Pigeon(
    id: 'pigeon_exe',
    number: 19,
    name: 'Pigeon.exe',
    rarity: PigeonRarity.legendary,
    hintFr: 'Erreur 404 : condition introuvable.',
    hintEn: 'Error 404: condition not found.',
    descriptionFr: 'Il semble parfois traverser les bancs.',
    descriptionEn: 'He occasionally clips through benches.',
    color: Color(0xFF62A29B),
    accessory: Icons.memory,
  ),
  Pigeon(
    id: 'king_pigeon',
    number: 20,
    name: 'King Pigeon',
    rarity: PigeonRarity.legendary,
    hintFr: 'Le parc doit être digne d’une couronne.',
    hintEn: 'The park must be worthy of a crown.',
    descriptionFr: 'Tous les pigeons prétendent être ses cousins.',
    descriptionEn: 'Every pigeon claims to be his cousin.',
    color: Color(0xFFD0AD4F),
    accessory: Icons.workspace_premium,
  ),
  Pigeon(
    id: 'miette',
    number: 21,
    name: 'Miette',
    rarity: PigeonRarity.common,
    hintFr: 'Elle aime les fleurs simples.',
    hintEn: 'She likes simple flowers.',
    descriptionFr: 'Elle collectionne les pétales minuscules.',
    descriptionEn: 'She collects tiny petals.',
    color: Color(0xFFB9A2A7),
    decorationIds: ['flowers'],
  ),
  Pigeon(
    id: 'roger',
    number: 22,
    name: 'Roger',
    rarity: PigeonRarity.common,
    hintFr: 'Un banc et du calme.',
    hintEn: 'A bench and some peace.',
    descriptionFr: 'Il vient lire le journal sans journal.',
    descriptionEn: 'He comes to read a newspaper without one.',
    color: Color(0xFF8C887E),
    decorationIds: ['bench'],
  ),
  Pigeon(
    id: 'baguettine',
    number: 23,
    name: 'Baguettine',
    rarity: PigeonRarity.rare,
    hintFr: 'Le pain frais lui rappelle Paris.',
    hintEn: 'Fresh bread reminds her of Paris.',
    descriptionFr: 'Elle laisse toujours une miette en pourboire.',
    descriptionEn: 'She always leaves a crumb as a tip.',
    color: Color(0xFFD8C19B),
    foodIds: ['bread'],
  ),
  Pigeon(
    id: 'professeur_plume',
    number: 24,
    name: 'Professeur Plume',
    rarity: PigeonRarity.rare,
    hintFr: 'Il cherche une pile de livres.',
    hintEn: 'He seeks a stack of books.',
    descriptionFr: 'Ses conférences durent plusieurs roucoulements.',
    descriptionEn: 'His lectures last several coos.',
    color: Color(0xFF758596),
    decorationIds: ['books'],
    accessory: Icons.school_outlined,
  ),
  Pigeon(
    id: 'fleur',
    number: 25,
    name: 'Fleur',
    rarity: PigeonRarity.rare,
    hintFr: 'Un jardin parfumé suffit.',
    hintEn: 'A fragrant garden will do.',
    descriptionFr: 'Elle refuse catégoriquement de marcher dans la boue.',
    descriptionEn: 'She categorically refuses to walk in mud.',
    color: Color(0xFFC89AAB),
    decorationIds: ['flowers'],
    weather: PigeonWeather.sunny,
    accessory: Icons.local_florist,
  ),
  Pigeon(
    id: 'radio_piaf',
    number: 26,
    name: 'Radio Piaf',
    rarity: PigeonRarity.epic,
    hintFr: 'Une radio pendant la journée.',
    hintEn: 'A radio during the day.',
    descriptionFr: 'Il connaît tous les refrains, rarement les paroles.',
    descriptionEn: 'He knows every tune, rarely the lyrics.',
    color: Color(0xFF7C6D91),
    decorationIds: ['radio'],
  ),
  Pigeon(
    id: 'monsieur_propre',
    number: 27,
    name: 'Monsieur Propre',
    rarity: PigeonRarity.epic,
    hintFr: 'Même une poubelle peut être élégante.',
    hintEn: 'Even a bin can be elegant.',
    descriptionFr: 'Il inspecte chaque miette avant de partir.',
    descriptionEn: 'He inspects every crumb before leaving.',
    color: Color(0xFFE2DDD2),
    decorationIds: ['trash'],
    weather: PigeonWeather.rainy,
  ),
  Pigeon(
    id: 'minuit',
    number: 28,
    name: 'Minuit',
    rarity: PigeonRarity.epic,
    hintFr: 'Des fleurs visibles au clair de lune.',
    hintEn: 'Flowers beneath the moonlight.',
    descriptionFr: 'Elle disparaît toujours avant l’aube.',
    descriptionEn: 'She always vanishes before dawn.',
    color: Color(0xFF55566B),
    decorationIds: ['flowers'],
    period: VisitPeriod.night,
  ),
  Pigeon(
    id: 'capitaine_plume',
    number: 29,
    name: 'Capitaine Plume',
    rarity: PigeonRarity.legendary,
    hintFr: 'Un festin premium pour un grand voyage.',
    hintEn: 'A premium feast for a great voyage.',
    descriptionFr: 'Il connaît une île entièrement faite de miettes.',
    descriptionEn: 'He knows an island made entirely of crumbs.',
    color: Color(0xFF765747),
    foodIds: ['premium_seeds'],
    accessory: Icons.sailing,
  ),
  Pigeon(
    id: 'celeste',
    number: 30,
    name: 'Céleste',
    rarity: PigeonRarity.legendary,
    hintFr: 'La radio murmure parfois son nom près d’un festin rare.',
    hintEn: 'The radio sometimes whispers her name near a rare feast.',
    descriptionFr: 'Elle apparaît lorsque le parc devient parfaitement calme.',
    descriptionEn: 'She appears when the park becomes perfectly still.',
    color: Color(0xFF9E92B8),
    foodIds: ['premium_seeds'],
    decorationIds: ['radio'],
    period: VisitPeriod.night,
    accessory: Icons.auto_awesome,
  ),
];
